### ISSUE TITLE
How to contribute to capacitor-community?

### ISSUE THREAD

**Issue by hinddeep** [capacitor-community/welcome#2]
This is the first time I'm trying to publish a plugin. After referring to the documentation I found out that I need to have access to the capacitor-community GitHub org and @capacitor-community npm scope. So how do I request access to the aforementioned repository and npm scope? 

_"Before adding your project to the capacitor-community org, make sure you have been granted access to the capacitor-community GitHub org and @capacitor-community npm scope."_

**Comment by imhoffd** [comment]
Hi @hinddeep! To contribute plugins to the Capacitor community, first find or create a proposal for your plugin/idea: https://github.com/capacitor-community/proposals/issues. Community members and Ionic team members are actively contributing to discussions there.

**Comment by hinddeep** [comment]
Okay, thank you! Will do so.
